// sveltejs/src/App.svelte
<script>
  let todos = [];
  let todoText = "";

  function addTodo() {
    todos = [...todos, todoText];
  }
</script>

<main>
  <ul>
    {#each todos as todo}
      <li>{todo}</li>
    {/each}
  </ul>
  <form on:submit|preventDefault={addTodo}>
    <input bind:value={todoText} />
    <input type="submit" value="Add Todo" />
  </form>
</main>

<style></style>

// angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular';
  todos: string[] = []
  todoText = ''

  addTodo(){
    this.todos.push(this.todoText)
  }
}

<ul>
  <li *ngFor="let todo of todos">{{todo}}</li>
</ul>

<form (ngSubmit)="addTodo()">
  <input name="todoText" [(ngModel)]="todoText">
  <input type="submit" value="Add Todo">
</form>
