// reactjs-typescript/src/App.tsx
import React from 'react';
import './App.css';

const App:React.FC = () => {
  const [todos, setTodos] = React.useState<string[]>([])
  const [inputValue, setInputValue] = React.useState('')

  const handleAdd = () => {
    setTodos(prev => [...prev, inputValue])
    setInputValue('')
  }

  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setInputValue(event.target.value)
  }

  return (
    <div className="App">
      <ul>
        {todos.map((each, index) =>
          <li key={index}>{each}</li>
        )}
      </ul>
      <div>
        <input value={inputValue} onChange={handleInputChange}/>
        <button onChange={handleAdd}>Add</button>
      </div>
    </div>
  );
}

export default App;

// solid/src/App.jsx
import { createSignal } from 'solid-js';

function App() {
  const [todos, setTodos] = createSignal([])
  let todoText;

  function addTodo(event){
    event.preventDefault()
    const next = [...todos(), todoText]
    setTodos(next)
  }

  function handleInput(event){
    todoText = event.target.value
  }

  return (
    <div>
      <ui>
        {todos().map(todo => (<li key={todo}>{todo}</li>))}
      </ui>

      <form onSubmit={addTodo}>
        <input type="text" onChange={handleInput}/>
        <input type="submit" value="Add Todo"/>
      </form>
    </div>
  );
}

export default App;
